In [80]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [81]:
df=pd.read_csv("customer_churn.csv")

In [82]:
data=df;
data

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0
...,...,...,...,...,...,...,...,...,...,...,...,...
64369,64370,45,Female,33,12,6,21,Basic,Quarterly,947,14,1
64370,64371,37,Male,6,1,5,22,Standard,Annual,923,9,1
64371,64372,25,Male,39,14,8,30,Premium,Monthly,327,20,1
64372,64373,50,Female,18,19,7,22,Standard,Monthly,540,13,1
64373,64374,52,Female,45,15,9,25,Standard,Monthly,696,22,1

In [83]:
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64374 entries, 0 to 64373
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         64374 non-null  int64
 1   Age                64374 non-null  int64
 2   Gender             64374 non-null  object
 3   Tenure             64374 non-null  int64
 4   Usage Frequency    64374 non-null  int64
 5   Support Calls      64374 non-null  int64
 6   Payment Delay      64374 non-null  int64
 7   Subscription Type  64374 non-null  object
 8   Contract Length    64374 non-null  object
 9   Total Spend        64374 non-null  int64
 10  Last Interaction   64374 non-null  int64
 11  Churn              64374 non-null  int64
dtypes: int64(9), object(3)
memory usage: 5.9+ MB

In [85]:
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency',
       'Support Calls', 'Payment Delay', 'Subscription Type',
       'Contract Length', 'Total Spend', 'Last Interaction', 'Churn'],
      dtype='object')

In [86]:
newcol=['Age','Tenure','Usage Frequency','Support calls','Payment Delay','Total Spend', 'Last Interaction', 'Churn']

In [87]:
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0

In [88]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
df['Gender']=label.fit_transform(df['Gender'])
df['Gender'].astype(int)

0        0
1        0
2        1
3        1
4        0
        ..
64369    0
64370    1
64371    1
64372    0
64373    0
Name: Gender, Length: 64374, dtype: int64

In [89]:
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,0,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,0,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,1,27,10,2,29,Premium,Annual,757,21,0
3,4,35,1,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,0,58,24,9,2,Standard,Annual,533,18,0

In [90]:
df['Subscription Type'].unique()

array(['Basic', 'Standard', 'Premium'], dtype=object)

In [91]:
df = pd.get_dummies(df, columns=['Subscription Type'], dtype=int)

In [92]:
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Contract Length,Total Spend,Last Interaction,Churn,Subscription Type_Basic,Subscription Type_Premium,Subscription Type_Standard
0,1,22,0,25,14,4,27,Monthly,598,9,1,1,0,0
1,2,41,0,28,28,7,13,Monthly,584,20,0,0,0,1
2,3,47,1,27,10,2,29,Annual,757,21,0,0,1,0
3,4,35,1,9,12,5,17,Quarterly,232,18,0,0,1,0
4,5,53,0,58,24,9,2,Annual,533,18,0,0,0,1

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64374 entries, 0 to 64373
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   CustomerID                  64374 non-null  int64
 1   Age                         64374 non-null  int64
 2   Gender                      64374 non-null  int64
 3   Tenure                      64374 non-null  int64
 4   Usage Frequency             64374 non-null  int64
 5   Support Calls               64374 non-null  int64
 6   Payment Delay               64374 non-null  int64
 7   Contract Length             64374 non-null  object
 8   Total Spend                 64374 non-null  int64
 9   Last Interaction            64374 non-null  int64
 10  Churn                       64374 non-null  int64
 11  Subscription Type_Basic     64374 non-null  int64
 12  Subscription Type_Premium   64374 non-null  int64
 13  Subscription Type_Standard  64374 non-null  int64
dtypes: int64(13), object(1)
memory usage: 6.9+ MB

In [94]:
df['Contract Length'].unique()

array(['Monthly', 'Annual', 'Quarterly'], dtype=object)

In [95]:
df = pd.get_dummies(df, columns=['Contract Length'], dtype=int)

In [96]:
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn,Subscription Type_Basic,Subscription Type_Premium,Subscription Type_Standard,Contract Length_Annual,Contract Length_Monthly,Contract Length_Quarterly
0,1,22,0,25,14,4,27,598,9,1,1,0,0,0,1,0
1,2,41,0,28,28,7,13,584,20,0,0,0,1,0,1,0
2,3,47,1,27,10,2,29,757,21,0,0,1,0,1,0,0
3,4,35,1,9,12,5,17,232,18,0,0,1,0,0,0,1
4,5,53,0,58,24,9,2,533,18,0,0,0,1,1,0,0

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64374 entries, 0 to 64373
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   CustomerID                  64374 non-null  int64
 1   Age                         64374 non-null  int64
 2   Gender                      64374 non-null  int64
 3   Tenure                      64374 non-null  int64
 4   Usage Frequency             64374 non-null  int64
 5   Support Calls               64374 non-null  int64
 6   Payment Delay               64374 non-null  int64
 7   Total Spend                 64374 non-null  int64
 8   Last Interaction            64374 non-null  int64
 9   Churn                       64374 non-null  int64
 10  Subscription Type_Basic     64374 non-null  int64
 11  Subscription Type_Premium   64374 non-null  int64
 12  Subscription Type_Standard  64374 non-null  int64
 13  Contract Length_Annual      64374 non-null  int64
 14  Contract Length_Monthly     64374 non-null  int64
 15  Contract Length_Quarterly   64374 non-null  int64
dtypes: int64(16)
memory usage: 7.9 MB

In [98]:
df.corr()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn,Subscription Type_Basic,Subscription Type_Premium,Subscription Type_Standard,Contract Length_Annual,Contract Length_Monthly,Contract Length_Quarterly
CustomerID,1.000000,0.043287,-0.085960,0.103296,-0.062699,0.164175,0.290684,-0.037068,-0.003718,0.529832,0.003732,-0.004401,0.000667,-0.006844,0.032902,-0.026510
Age,0.043287,1.000000,0.001800,-0.007763,-0.038331,0.005014,-0.016132,0.006490,-0.000148,0.063457,-0.001585,-0.004582,0.006161,-0.000740,0.001311,-0.000585
Gender,-0.085960,0.001800,1.000000,0.029418,-0.006907,0.035418,-0.058578,0.029337,-0.000472,-0.164549,-0.005664,0.000281,0.005380,0.022167,-0.028741,0.006856
Tenure,0.103296,-0.007763,0.029418,1.000000,0.023485,0.060065,0.055963,0.009474,0.005770,0.195327,-0.002201,-0.002881,0.005078,0.001039,-0.003306,0.002310
Usage Frequency,-0.062699,-0.038331,-0.006907,0.023485,1.000000,-0.014072,0.031132,0.001527,-0.009192,-0.115098,0.000381,0.000364,-0.000744,-0.013769,0.008066,0.005677
Support Calls,0.164175,0.005014,0.035418,0.060065,-0.014072,1.000000,0.064298,0.021750,0.001666,0.304631,0.005258,-0.005009,-0.000250,0.010961,-0.016492,0.005705
Payment Delay,0.290684,-0.016132,-0.058578,0.055963,0.031132,0.064298,1.000000,-0.031119,-0.008076,0.557386,0.003297,-0.003979,0.000680,-0.016042,0.028522,-0.012800
Total Spend,-0.037068,0.006490,0.029337,0.009474,0.001527,0.021750,-0.031119,1.000000,-0.007692,-0.078867,-0.000311,0.006925,-0.006608,-0.018179,0.024744,-0.006814
Last Interaction,-0.003718,-0.000148,-0.000472,0.005770,-0.009192,0.001666,-0.008076,-0.007692,1.000000,-0.002818,0.004521,-0.005186,0.000662,-0.003731,0.000819,0.002925
Churn,0.529832,0.063457,-0.164549,0.195327,-0.115098,0.304631,0.557386,-0.078867,-0.002818,1.000000,0.012869,-0.012334,-0.000539,-0.016284,0.061464,-0.046000
Subscription Type_Basic,0.003732,-0.001585,-0.005664,-0.002201,0.000381,0.005258,0.003297,-0.000311,0.004521,0.012869,1.000000,-0.499231,-0.500647,0.000956,-0.000087,-0.000874
Subscription Type_Premium,-0.004401,-0.004582,0.000281,-0.002881,0.000364,-0.005009,-0.003979,0.006925,-0.005186,-0.012334,-0.499231,1.000000,-0.500122,-0.003454,0.003127,0.000304
Subscription Type_Standard,0.000667,0.006161,0.005380,0.005078,-0.000744,-0.000250,0.000680,-0.006608,0.000662,-0.000539,-0.500647,-0.500122,1.000000,0.002496,-0.003037,0.000570
Contract Length_Annual,-0.006844,-0.000740,0.022167,0.001039,-0.013769,0.010961,-0.016042,-0.018179,-0.003731,-0.016284,0.000956,-0.003454,0.002496,1.000000,-0.510933,-0.488313
Contract Length_Monthly,0.032902,0.001311,-0.028741,-0.003306,0.008066,-0.016492,0.028522,0.024744,0.000819,0.061464,-0.000087,0.003127,-0.003037,-0.510933,1.000000,-0.500669
Contract Length_Quarterly,-0.026510,-0.000585,0.006856,0.002310,0.005677,0.005705,-0.012800,-0.006814,0.002925,-0.046000,-0.000874,0.000304,0.000570,-0.488313,-0.500669,1.000000

In [99]:
from sklearn.model_selection import train_test_split
X=df.drop(['Churn','CustomerID'],axis=1)
Y=df['Churn']
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

In [100]:
X_train

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Subscription Type_Basic,Subscription Type_Premium,Subscription Type_Standard,Contract Length_Annual,Contract Length_Monthly,Contract Length_Quarterly
13468,56,0,42,11,0,10,793,15,0,1,0,0,0,1
20118,54,1,60,5,3,9,610,24,0,0,1,0,0,1
48411,31,1,12,2,9,7,222,30,1,0,0,1,0,0
42125,33,0,22,17,5,25,648,20,0,1,0,0,1,0
55119,39,0,28,30,2,25,983,22,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62570,50,1,38,11,5,28,568,5,0,1,0,0,0,1
38158,53,1,44,30,3,3,447,21,0,1,0,0,1,0
860,33,0,47,9,2,26,454,6,0,0,1,0,0,1
15795,24,1,57,19,10,9,948,27,0,1,0,1,0,0
56422,33,0,34,19,6,17,554,2,0,0,1,0,0,1

In [101]:
from sklearn.preprocessing import StandardScaler
Scaler=StandardScaler()
X_train_scaled=Scaler.fit_transform(X_train)
X_test_scaled=Scaler.transform(X_test)

In [102]:
X_test_scaled

array([[ 0.93574903,  1.0699573 , -0.69912053, ..., -0.70820894,
         1.37670505, -0.68692255],
       [-1.00122   ,  1.0699573 , -0.28992695, ..., -0.70820894,
        -0.726372  ,  1.4557682 ],
       [ 1.65314497, -0.93461673,  1.63912853, ..., -0.70820894,
        -0.726372  ,  1.4557682 ],
       ...,
       [ 0.72053025, -0.93461673,  1.05456626, ..., -0.70820894,
        -0.726372  ,  1.4557682 ],
       [-1.57513675, -0.93461673,  1.40530362, ...,  1.41201267,
        -0.726372  , -0.68692255],
       [ 0.2183531 , -0.93461673,  0.93765381, ..., -0.70820894,
         1.37670505, -0.68692255]])

In [103]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()
logistic.fit(X_train_scaled,y_train)

LogisticRegression()

In [104]:
prediction=logistic.predict(X_test_scaled)

In [105]:
prediction

array([0, 0, 1, ..., 1, 0, 0])

In [106]:
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report

In [107]:
accuracy_score(y_test,prediction)

0.831611650485437

In [108]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors= 5)
knn.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [109]:
knn_prediction=knn.predict(X_test_scaled)

In [110]:
accuracy_score(y_test,knn_prediction)

0.9096699029126214

In [111]:
confusion_matrix(y_test,knn_prediction)

array([[6021,  772],
       [ 391, 5691]])

In [115]:
from sklearn.tree import DecisionTreeClassifier
dt_model=DecisionTreeClassifier(max_depth=5)
dt_model.fit(X_train_scaled,y_train)

DecisionTreeClassifier(max_depth=5)

In [116]:
dt_pred=dt_model.predict(X_test_scaled)

In [117]:
accuracy_score(y_test,dt_pred)

0.9596893203883495

In [118]:
print("Train Accuracy:", dt_model.score(X_train_scaled, y_train))
print("Test Accuracy:", dt_model.score(X_test_scaled, y_test))

Train Accuracy: 0.9563292491116332
Test Accuracy: 0.9596893203883495